# Setup
title: AGRN-VC demo
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:       https://twiz0311.github.io/AGRN-VC/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown